---
language: node_js
sudo: false
dist: trusty
node_js:
  - "6"

addons:
  chrome: stable

cache:
  yarn: true

branches:
  only:
    - master
    - beta
    - release
    # npm version tags
    - /^v\d+\.\d+\.\d+/

stages:
  - test
  - specific version tests
  - advance warning tests

jobs:
  fail_fast: true
  allow_failures:
   - env: EMBER_TRY_SCENARIO=ember-canary
   - env: NAME=floating dependencies

  include:
    # runs tests with current locked deps and linting
    - stage: test
      env: NAME=test # used only to make Travis UI show description
      script: yarn test

    # runs tests against each supported Ember version
    - stage: specific version tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release

    # runs tests against future Ember versions
    - stage: advance warning tests
      env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: NAME=floating dependencies # used only to make Travis UI show description
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
