---
language: node_js
sudo: false
dist: trusty
node_js:
  - '10'

addons:
  chrome: stable

cache:
  yarn: true
env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

stages:
  - test
  - specific version tests
  - advance warning tests

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=canary-channel
    - env: NAME=floating dependencies

  include:
    # runs tests with current locked deps and linting
    - stage: test
      env: NAME=test # used only to make Travis UI show description
      script:
        - yarn lint:js
        - yarn test
        - yarn test:node

    - stage: feature flagged features
      script: node_modules/.bin/ember try:one canary-channel --- ember test  --query enableoptionalfeatures
    # runs tests against each supported Ember version
    - stage: specific version tests
      env: EMBER_TRY_SCENARIO=release-channel
    - env: EMBER_TRY_SCENARIO=release-n-1
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-data-packages-3.14
    - env: EMBER_TRY_SCENARIO=ember-data-packages-latest
    - env: EMBER_TRY_SCENARIO=ember-data-packages-beta
    - env: EMBER_TRY_SCENARIO=ember-data-packages-canary

    # runs tests against future Ember versions
    - stage: advance warning tests
      env: EMBER_TRY_SCENARIO=canary-channel
    - env: NAME=floating dependencies # used only to make Travis UI show description
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - commitlint-travis
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
